## Arrays

**Task**

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

*Input Format*

A single line of input containing space separated numbers.

*Output Format*

Print the reverse NumPy array with type float.

In [8]:
import numpy

def arrays(arr):
    return(numpy.array(arr[::-1], float))
    

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


## Shape and Reshape

**shape**

The shape tool gives a tuple of array dimensions and can be used to change the dimensions of an array.

**reshape**

The reshape tool gives a new shape to an array without changing its data. It creates a new array and does not modify the original array itself. 

In [14]:
import numpy as np

print(np.array(input().split(), int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [36]:
import numpy
N,M = [int(x) for x in input().strip().split()]
arr = []
for _ in range(N):
    arr.append([int(x) for x in input().strip().split()])
print(numpy.transpose(arr))
print(numpy.array(arr).flatten())

2 2
1 3
3 4
[[1 3]
 [3 4]]
[1 3 3 4]


## Concatenate

In [45]:
import numpy as np
n,m,p = map(int, input().split())
arr1 = np.array([input().split()  for _ in range(n)],int )
arr2 = np.array([input().split()  for _ in range(m)],int )

print(np.concatenate((arr1,arr2),axis =0))

4 3 2
1 2
1 2
1 2
1 2
1 2
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]]


## Zeros and Ones

In [15]:
import numpy as np
N = tuple(map(int, input().split()))
print(np.zeros(N,int))
print(np.ones(N,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity



In [57]:
import numpy as np
np.set_printoptions(sign=' ')
N,M = map(int,  input().split())
print(np.eye(N,M))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics



In [60]:
import numpy as np
def arrays(arr, arr1, arr2):
    arr = np.array(arr, dtype = int)
    arr1 = np.array([arr1], dtype = int)
    arr2 = np.array([arr2], dtype = int)

    add = np.add(arr1,arr2)
    sub = np.subtract(arr1,arr2)
    mul = np.multiply(arr1,arr2)
    div = np.floor_divide(arr1,arr2)
    mod = np.mod(arr1,arr2)
    power = np.power(arr1, arr2)
    return add, sub, mul, div, mod, power

arr = input().strip().split(' ')
arr1 = input().strip().split(' ')
arr2 = input().strip().split(' ')
add, sub, mul, div, mod, power = arrays(arr, arr1, arr2)
print(add)
print(sub)
print(mul)
print(div)
print(mod)
print(power)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


<h2>Floor, Ceil and Rint</h2>

In [67]:
import numpy as np

N = np.array(input().split(), float)

print(np.floor(N), np.ceil(N), np.rint(N), sep = '\n')

1.1 2.2 3.3
[ 1.  2.  3.]
[ 2.  3.  4.]
[ 1.  2.  3.]


<h2>Sum and Prod</h2>

In [71]:
import numpy

N, M = map(int, input().split())

array = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(array, axis = 0), axis = None))

2 2 
1 2
3 4
24


## Min and Max



In [74]:
import numpy as np
N,M = map(int, input().split())
A = np.array([input().split() for i in range(N)], dtype = int)
C = np.max(np.min(A, axis = 1), axis = 0)
print(C)

1 2
3 4
3


<h2>Mean, Var, and Std

</h2>

In [3]:
import numpy as np
N,M = map(int, input().split())
A = np.array([input().split() for _ in range(N)], dtype = int)
print(np.mean(A, axis =1))
print(np.var(A, axis = 0))
print(np.std(A))

4 5
5 6
7 8
9 10
3 4
[5.5 7.5 9.5 3.5]
[5. 5.]
2.29128784747792


In [4]:
import numpy as np
n, m = map(int, input().split())
list1 = []
for i in range(n):
    l = list(map(int, input().split()))
    list1.append(l)
arr = np.array(list1)
np.set_printoptions(legacy = '1.13')
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print(np.std(arr, axis = None))



    

4 5
6 7
8 9
10 11
5 6
[ 6.5  8.5 10.5  5.5]
[3.6875 3.6875]
1.984313483298443


In [5]:
import numpy as np
#np.set_printoptions(legacy = '1.13')
n, m = map(int, input().split())

arr = np.array([input().split() for _ in range(n)], float)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
arr=np.std(arr,axis=None)
print(np.around(arr,decimals=11))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.11803398875


<h2>Dot and Cross</h2>

In [72]:
import numpy as np
N = int(input())
A = np.array([input().split() for i in range(N)], dtype = int)
B = np.array([input().split() for i in range(N)], dtype = int)
C = np.dot(A,B)
print(C)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


## Inner and Outer

In [1]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print("------------")
print(np.inner(A,B))
print("------------")
print(np.outer(A,B))

1 2
3 4
------------
11
------------
[[3 4]
 [6 8]]


## Polynomials

In [58]:
import numpy as np
arr = [float(x) for x in input().split()]
x = float(input())

print(np.polyval(arr, x))

1.1 2 3
0
3.0


## Linear Algebra 

In [52]:
import numpy as np
arr = [float(x) for x in input().split()]
x = float(input())

print(np.polyval(arr, x))

1.1 2 3
0
3.0
